export enum JobEventType {
  JOB_CREATED = 'JOB_CREATED',
  UPLOAD_COMPLETED = 'UPLOAD_COMPLETED',
  PROCESSING_STARTED = 'PROCESSING_STARTED',
  CLIP_GENERATED = 'CLIP_GENERATED',
  ZIP_GENERATED = 'ZIP_GENERATED',
  JOB_COMPLETED = 'JOB_COMPLETED',
  JOB_FAILED = 'JOB_FAILED',
  JOB_EXPIRED = 'JOB_EXPIRED'
}
